language: python
dist: xenial
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - pip install -r tests/requirements.txt
script:
  - python -m pytest
  - python -m sphinx docs/ docs/_build/ -b html -W -D nbsphinx_execute='always'
  - python -m sphinx docs/ docs/_build/ -b linkcheck -W
